name: Test

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: ./.github/actions/build.yml@v1

    - name: Test
      run: dotnet test --no-restore --verbosity normal