name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    uses: a7mdfre7at/GihubActionDemo/.github/workflows/build.yml@master
    steps:
    - name: Test
      run: dotnet test --no-restore --verbosity normal